SUPABASE_URL = "https://gscrjjtfawnudycbtqxl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzY3JqanRmYXdudWR5Y2J0cXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NDYyOTQsImV4cCI6MjA0ODAyMjI5NH0.yQKItjeX1pYnjdah0zH4kKpT8ZkcpmHmDW1PKakRvFg"
